services:
  files-uploader:
    image: ghcr.io/xhunter74/files-uploader:latest
    hostname: files-uploader
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: 'Production'
      AppSettings__AzureConnectionString: 'Your Azure Storage Connection String'
      AppSettings__ScanIntervalMinutes: 1
      Serilog__MinimumLevel__Default: 'Debug'
    build:
      args:
        PROJECT_NAME: FilesUploader
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./logs:/app/Logs"
      - "./backups:/app/Backups"
 
  